website/auth.py
from flask import Blueprint, flash, render_template, request, session

from . import db

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "GET":
        return render_template(
            "login.html",
            session=session,
        )
    elif request.method == "POST":
        customer_query = r"""SELECT customers.customer_id,
                                    customers.first_name,
                                    customers.last_name
                                FROM customers
                                WHERE customers.ssn = %s
                        """

        employee_query = r"""SELECT employees.employee_id,
                                    employees.first_name,
                                    employees.last_name
                                FROM employees
                                WHERE employees.ssn = %s
                        """

        cursor = db.cursor()
        if request.form.get("customer-or-employee-radio") == "customer":
            cursor.execute(customer_query, (request.form.get("ssn"),))
        elif request.form.get("customer-or-employee-radio") == "employee":
            cursor.execute(employee_query, (request.form.get("ssn"),))

        user = cursor.fetchone()
        if user is None:
            flash("Invalid SSN", "danger")
        else:
            session["user"] = {
                "type": request.form.get("customer-or-employee-radio"),
                "id": user[0],
                "first_name": user[1],
                "last_name": user[2],
            }
        return render_template(
            "login.html",
            session=session,
        )


@auth.route("/logout")
def logout():
    session["user"] = None
    return render_template("login.html", session=session)


@auth.route("/sign-up/", methods=["GET", "POST"])
def sign_up():
    cursor = db.cursor()

    if request.method == "GET":
        positions_query = r"""SELECT positions.position_id,
                        positions.position_name
                    FROM positions
                """
        cursor.execute(positions_query)
        positions = cursor.fetchall()

        hotels_query = r"""SELECT
                            hotels.hotel_id,
                            chains.chain_name,
                            CONCAT(hotels.street_number, ' ', hotels.street_name, ', ', hotels.zip) as address
                            FROM hotels
                            JOIN chains ON hotels.chain_id = chains.chain_id
                        """
        cursor.execute(hotels_query)
        hotels = cursor.fetchall()
        return render_template(
            "sign_up.html", positions=positions, hotels=hotels, inserted_id=None
        )
    elif request.method == "POST":
        customer_query = r"""INSERT INTO customers
                            (ssn, first_name, middle_initial, last_name,
                             street_number, street_name, apt_number,
                             city, province_or_state, country, zip)
                            VALUES
                            (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                            RETURNING customer_id;
                        """
        employee_query = r"""INSERT INTO employees
                            (ssn, first_name, middle_initial, last_name,
                             street_number, street_name, apt_number,
                             city, province_or_state, country, zip,
                             position_id, hotel_id)
                            VALUES
                            (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                            RETURNING employee_id;
                        """

        if request.form.get("customer-or-employee-radio") == "customer":
            cursor.execute(
                customer_query,
                (
                    request.form.get("ssn"),
                    request.form.get("first-name"),
                    request.form.get("middle-initial"),
                    request.form.get("last-name"),
                    request.form.get("street-number"),
                    request.form.get("street-name"),
                    request.form.get("apt-number"),
                    request.form.get("city"),
                    request.form.get("province-or-state"),
                    request.form.get("country"),
                    request.form.get("zip"),
                ),
            )
        elif request.form.get("customer-or-employee-radio") == "employee":
            cursor.execute(
                employee_query,
                (
                    request.form.get("ssn"),
                    request.form.get("first-name"),
                    request.form.get("middle-initial"),
                    request.form.get("last-name"),
                    request.form.get("street-number"),
                    request.form.get("street-name"),
                    request.form.get("apt-number"),
                    request.form.get("city"),
                    request.form.get("province-or-state"),
                    request.form.get("country"),
                    request.form.get("zip"),
                    request.form.get("position"),
                    request.form.get("hotel"),
                ),
            )
        inserted_id = cursor.fetchone()
        if inserted_id is not None:
            inserted_id = inserted_id[0]
            db.commit()
        cursor.close()
        return render_template("sign_up.html", inserted_id=inserted_id)

website/templates/available_rooms.html
{% extends "base.html" %} {% block title %}Rent{% endblock %} {% block content
%}
<table class="table table-striped">
  <thead>
    <tr>
      <th>Chain</th>
      <th>Hotel ID</th>
      <th>Stars</th>
      <th># Rooms</th>
      <th>Country</th>
      <th>Province/State</th>
      <th>City</th>
      <th>Address</th>
      <th>Room No.</th>
      <th>Capacity</th>
      <th>View</th>
      <th>Price</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for room in rooms %}
    <tr>
      <td>{{ room[0] }}</td>
      <td>{{ room[-1] }}</td>
      <td>{{ room[1] }}</td>
      <td>{{ room[2] }}</td>
      <td>{{ room[3] }}</td>
      <td>{{ room[4] }}</td>
      <td>{{ room[5] }}</td>
      <td>{{ room[6] }}</td>
      <td>{{ room[7] }}</td>
      <td>{{ room[8] }}</td>
      <td>{{ room[9] }}</td>
      <td>{{ room[10] }}</td>
      <td>
        <form
          action="{{ url_for('views.rent', customer_ssn=customer_ssn, hotel_id=room[11], room_number=room[7], price=room[10], start_date=start_date, end_date=end_date) }}"
          method="get"
        >
          <button type="submit" class="btn btn-dark">Rent</button>
        </form>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <div class="container-fluid text-center">
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %}
    <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
    {% endfor %} {% endif %} {% endwith %}
  </div>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">eHotels</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          <a class="nav-item nav-link" id="chains" href="/chains">Chains</a>
          <a class="nav-item nav-link" id="hotels" href="/hotels">Hotels</a>
          <a class="nav-item nav-link" id="rooms" href="/rooms">Rooms</a>
          {% if session.get("user")is not none and
          session.get("user").get("type") == "employee" %}
          <a class="nav-item nav-link" id="bookings" href="/bookings"
            >Bookings</a
          >
          <a class="nav-item nav-link" id="rentals" href="/rentals">Rentals</a>
          <a class="nav-item nav-link" id="rent" href="/rent">Rent</a>
          {% endif %}
          <a class="nav-item nav-link" id="view-1" href="/view-one">View 1</a>
          <a class="nav-item nav-link" id="view-2" href="/view-two">View 2</a>
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
        </div>
      </div>
      <div class="d-flex text-right align-items-center">
        <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
        {% if session.get("user") is none %}
        <span class="badge badge-secondary" style="padding: 8px">
          Not Logged In
        </span>
        {% else %}
        <form action="/edit-user" method="get">
          <button type="submit" class="btn btn-light">
            {{ session.get("user").get("type") }} {{
            session.get("user").get("id") }}
          </button>
        </form>
        {% endif %}
      </div>
    </nav>
    <div class="container-fluid">{% block content %}{% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    {% block script %}{% endblock %}
  </body>
</html>

website/templates/edit_email.html
{% extends "base.html" %}
{% block title %}Edit Chain Email Address{% endblock %}
{% block
    content %}
    <div class="container text-center">
        <table class="table table-striped">
            <tr>
                <td>Chain ID</td>
                <td>{{ chain_id }}</td>
            </tr>
            <tr>
                <td>Chain Name</td>
                <td>{{ chain_name }}</td>
            </tr>
        </table>
    </div>
    <br />
    <form action="{{ url_for('views.edit_email', chain_id=chain_id, email_id=email_id) }}"
          method="post">
        <div class="form-row">
            <div class="form-group col">
                <label for="email-address">Email Address</label>
                <input type="text"
                       class="form-control"
                       id="email-address"
                       name="email-address"
                       value="{{ email[0] }}"/>
            </div>
            <div class="form-group col">
                <label for="email-description">Description</label>
                <input type="text"
                       class="form-control"
                       id="email-description"
                       name="email-description"
                       value="{{ email[1] }}"/>
            </div>
        </div>
        <br />
        <div class="container text-center">
            <button type="submit" class="btn btn-dark">Edit Email Address</button>
        </div>
    </form>
{% endblock %}

website/templates/edit_hotel_address.html
{% extends "base.html" %}
{% block title %}Edit Hotel{% endblock %}
{% block
    content %}
    <div class="container text-center">
        <table class="table table-striped">
            <tr>
                <td>Hotel ID</td>
                <td>{{ hotel_id }}</td>
            </tr>
        </table>
    </div>
    <br />
    <form action="{{ url_for('views.edit_hotel_address', hotel_id=hotel_id) }}"
          method="post">
        <div class="form-row">
            <div class="form-group col">
                <label for="street-number">Street Number</label>
                <input type="text"
                       class="form-control"
                       name="street-number"
                       id="street-number"
                       value="{{ hotel[0] }}"/>
            </div>
            <div class="form-group col">
                <label for="street-name">Street Name</label>
                <input type="text"
                       class="form-control"
                       name="street-name"
                       id="street-name"
                       value="{{ hotel[1] }}"/>
            </div>
            <div class="form-group col">
                <label for="city">City</label>
                <input type="text"
                       class="form-control"
                       name="city"
                       id="city"
                       value="{{ hotel[2] }}"/>
            </div>
            <div class="form-group col">
                <label for="province-or-state">Province/State</label>
                <input type="text"
                       class="form-control"
                       name="province-or-state"
                       id="province-or-state"
                       value="{{ hotel[3] }}"/>
            </div>
            <div class="form-group col">
                <label for="country">Country</label>
                <input type="text"
                       class="form-control"
                       name="country"
                       id="country"
                       value="{{ hotel[4] }}"/>
            </div>
            <div class="form-group col">
                <label for="zip">Zip</label>
                <input type="text"
                       class="form-control"
                       name="zip"
                       id="zip"
                       value="{{ hotel[5] }}"/>
            </div>
        </div>
        <div class="container text-center">
            <button type="submit" class="btn btn-dark">Edit Hotel Address</button>
        </div>
    </form>
{% endblock %}

website/templates/edit_office.html
{% extends "base.html" %} {% block title %}Edit Chain Office{% endblock %} {%
block content %}
<div class="container text-center">
  <table class="table table-striped">
    <tr>
      <td>Chain ID</td>
      <td>{{ chain_id }}</td>
    </tr>
    <tr>
      <td>Chain Name</td>
      <td>{{ chain_name }}</td>
    </tr>
  </table>
</div>
<br />
<form
  action="{{ url_for('views.edit_office', chain_id=chain_id, office_id=office_id) }}"
  method="post"
>
  <div class="form-row">
    <div class="form-group col">
      <label for="street-number">Street Number</label>
      <input
        type="text"
        class="form-control"
        id="street-number"
        name="street-number"
        value="{{ office[0] }}"
      />
    </div>
    <div class="form-group col">
      <label for="street-name">Street Name</label>
      <input
        type="text"
        class="form-control"
        id="street-name"
        name="street-name"
        value="{{ office[1] }}"
      />
    </div>
    <div class="form-group col">
      <label for="apt-number">Apt Number</label>
      <input
        type="text"
        class="form-control"
        id="apt-number"
        name="apt-number"
        value="{{ office[2] }}"
      />
    </div>
    <div class="form-group col">
      <label for="city">City</label>
      <input
        type="text"
        class="form-control"
        id="city"
        name="city"
        value="{{ office[3] }}"
      />
    </div>
    <div class="form-group col">
      <label for="province-or-state">Province or State</label>
      <input
        type="text"
        class="form-control"
        id="province-or-state"
        name="province-or-state"
        value="{{ office[4] }}"
      />
    </div>
    <div class="form-group col">
      <label for="country">Country</label>
      <input
        type="text"
        class="form-control"
        id="country"
        name="country"
        value="{{ office[5] }}"
      />
    </div>
    <div class="form-group col">
      <label for="zip">Zip</label>
      <input
        type="text"
        class="form-control"
        id="zip"
        name="zip"
        value="{{ office[6] }}"
      />
    </div>
  </div>
  <br />
  <div class="container text-center">
    <button type="submit" class="btn btn-dark">Edit Office Address</button>
  </div>
</form>
{% endblock %}

website/templates/edit_phone.html
{% extends "base.html" %}
{% block title %}Edit Chain Phone Number{% endblock %}
{% block
    content %}
    <div class="container text-center">
        <table class="table table-striped">
            <tr>
                <td>Chain ID</td>
                <td>{{ chain_id }}</td>
            </tr>
            <tr>
                <td>Chain Name</td>
                <td>{{ chain_name }}</td>
            </tr>
        </table>
    </div>
    <br />
    <form action="{{ url_for('views.edit_phone', chain_id=chain_id, phone_id=phone_id) }}"
          method="post">
        <div class="form-row">
            <div class="form-group col">
                <label for="phone-number">Phone Number</label>
                <input type="text"
                       class="form-control"
                       id="phone-number"
                       name="phone-number"
                       value="{{ phone[0] }}"/>
            </div>
            <div class="form-group col">
                <label for="phone-description">Description</label>
                <input type="text"
                       class="form-control"
                       id="phone-description"
                       name="phone-description"
                       value="{{ phone[1] }}"/>
            </div>
        </div>
        <br />
        <div class="container text-center">
            <button type="submit" class="btn btn-dark">Edit Phone Number</button>
        </div>
    </form>
{% endblock %}

website/templates/edit_room_details.html
{% extends "base.html" %} {% block title %}Edit User{% endblock %} {% block
content %}
<div class="container text-center">
  <table class="table table-striped">
    <tr>
      <td>Hotel ID</td>
      <td>{{ hotel_id }}</td>
    </tr>
    <tr>
      <td>Room Number</td>
      <td>{{ room[0] }}</td>
    </tr>
  </table>
</div>
<form action="{{ url_for('views.edit_room_details', hotel_id=hotel_id, room_number=room_number) }}" method="post">
  <div class="form-row">
    <div class="form-group col">
      <label for="capacity">Capacity</label>
      <input
        type="text"
        class="form-control"
        id="capacity"
        name="capacity"
        value="{{ room[1] }}"
      />
    </div>
    <div class="form-group col">
      <label for="price">Price</label>
      <input
        type="text"
        class="form-control"
        id="price"
        name="price"
        value="{{ room[2] }}"
      />
    </div>
        <div class="form-group col">
        <label for="extensible">Extensible</label>
        <select id="extensible" class="form-control" name="extensible">
          <option value="True" {% if room[3] == 1 %} selected {% endif %}>Yes</option>
          <option value="False" {% if room[3] == 0 %} selected {% endif %}>No</option>
        </select>
        </div>
        <div class="form-group col">
        <label for="tv">TV</label>
        <select id="tv" class="form-control" name="tv">
          <option value="True" {% if room[4] == 1 %} selected {% endif %}>Yes</option>
          <option value="False" {% if room[4] == 0 %} selected {% endif %}>No</option>
        </select>
        </div>
        <div class="form-group col">
        <label for="air_condition">Air Condition</label>
        <select id="air_condition" class="form-control" name="air_condition">
          <option value="True" {% if room[5] == 1 %} selected {% endif %}>Yes</option>
          <option value="False" {% if room[5] == 0 %} selected {% endif %}>No</option>
        </select>
        </div>
        <div class="form-group col">
        <label for="fridge">Fridge</label>
        <select id="fridge" class="form-control" name="fridge">
          <option value="True" {% if room[6] == 1 %} selected {% endif %}>Yes</option>
          <option value="False" {% if room[6] == 0 %} selected {% endif %}>No</option>
        </select>
        </div>
        <div class="form-group col">
        <label for="view">View</label>
        <select id="view" class="form-control" name="view">
            {% for view in views %}
                <option value="{{ view[0] }}" {% if room[7] == view[1] %} selected {% endif %}>{{ view[1] }}</option>
            {% endfor %}
        </select>
        </div>
  </div>
    <br/>
  <div class="container text-center">
    <button type="submit" class="btn btn-dark">Edit Room Details</button>
  </div>
</form>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
    <div class="d-flex flex-column justify-content-center align-items-center">
        <hr/>
        <h1 class="text-center">Welcome to the eHotels Portal</h1>
        <hr/>
        <div class="card text-center w-50">
            <div class="card-body">
                <table class="table table-striped table-bordered">
                    <tr>
                        <td class="text-left">Course</td>
                        <td class="text-left">CSI 2132 - Databases I</td>
                    </tr>
                    <tr>
                        <td class="text-left">Group</td>
                        <td class="text-left">77</td>
                    </tr>
                    <tr>
                        <td class="text-left">Name</td>
                        <td class="text-left">Matthew Sia</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
    {% if session.get("user") is none %}
        <form class="text-center"
              action="{{ url_for('auth.login') }}"
              method="post">
            <br/>
            <p>Select Account Type</p>
            <div class="form-check form-check-inline">
                <input class="form-check-input"
                       type="radio"
                       value="customer"
                       name="customer-or-employee-radio"
                       id="customer-radio"
                       checked/>
                <label class="form-check-label" for="customer-radio">Customer</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input"
                       type="radio"
                       value="employee"
                       name="customer-or-employee-radio"
                       id="employee-radio"/>
                <label class="form-check-label" for="employee-radio">Employee</label>
            </div>
            <br/>
            <br/>
            <div class="container col-2">
                <label for="ssn">SSN</label>
                <input type="text"
                       name="ssn"
                       id="ssn"
                       class="form-control"
                       placeholder="SSN"/>
            </div>
            <br/>
            <button type="submit" class="form-check btn btn-dark">Login</button>
        </form>
    {% else %}
        <div class="container text-center">
            <h1>You are logged in as {{ session.get("user").get("type") }} {{ session.get("user").get("id") }}</h1>
            <br/>
            <table class="table table-striped">
                <tr>
                    <td>First Name</td>
                    <td>{{ session.get("user").get("first_name") }}</td>
                </tr>
                <tr>
                    <td>Last Name</td>
                    <td>{{ session.get("user").get("last_name") }}</td>
                </tr>
            </table>
        </div>
        <br/>
        <div class="container text-center">
            <button class="btn btn-dark"
                    onclick="window.location.href = '{{ url_for('auth.logout') }}'">Logout</button>
        </div>
    {% endif %}
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}
{% block content %}
    {% if inserted_id %}
        <div class="container text-center">
            <h1>Sign Up</h1>
            <p>Account created successfully!</p>
            <p>Your account ID is {{ inserted_id }}.</p>
            <p>
                Click <a href="{{ url_for('auth.login') }}">here</a> to log in.
            </p>
        </div>
    {% else %}
        <form action="{{ url_for('auth.sign_up') }}" method="post">
            <div class="form-row">
                <div class="form-group col">
                    <label for="first-name">First Name</label>
                    <input type="text" class="form-control" id="first-name" name="first-name"/>
                </div>
                <div class="form-group col">
                    <label for="middle-initial">Middle Initial</label>
                    <input type="text"
                           class="form-control"
                           id="middle-initial"
                           name="middle-initial"/>
                </div>
                <div class="form-group col">
                    <label for="last-name">Last Name</label>
                    <input type="text" class="form-control" id="last-name" name="last-name"/>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col">
                    <label for="street-number">Street Number</label>
                    <input type="text"
                           class="form-control"
                           id="street-number"
                           name="street-number"/>
                </div>
                <div class="form-group col">
                    <label for="street-name">Street Name</label>
                    <input type="text" class="form-control" id="street-name" name="street-name"/>
                </div>
                <div class="form-group col">
                    <label for="apt-number">Apt Number</label>
                    <input type="text" class="form-control" id="apt-number" name="apt-number"/>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col">
                    <label for="city">City</label>
                    <input type="text" class="form-control" id="city" name="city"/>
                </div>
                <div class="form-group col">
                    <label for="province-or-state">Province/State</label>
                    <input type="text"
                           class="form-control"
                           id="province-or-state"
                           name="province-or-state"/>
                </div>
                <div class="form-group col">
                    <label for="country">Country</label>
                    <input type="text" class="form-control" id="country" name="country"/>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col">
                    <label for="zip">Zip</label>
                    <input type="text" class="form-control" id="zip" name="zip"/>
                </div>
                <div class="form-group col">
                    <label for="ssn">SSN</label>
                    <input type="text"
                           class="form-control"
                           id="ssn"
                           name="ssn"
                           placeholder="123-456-789"/>
                </div>
            </div>
            <div class="form-row" id="employee-extra-fields" style="display: flex;">
                <div class="form-group col">
                    <label for="position">Position</label>
                    <select id="position" class="form-control" name="position">
                        <option>
                        </option>
                        {% for position in positions %}
                            <option value="{{ position[0] }}">
                                {{ position[1] }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group col">
                    <label for="hotel">Hotel</label>
                    <select id="hotel" class="form-control" name="hotel">
                        <option>
                        </option>
                        {% for hotel in hotels %}
                            <option value="{{ hotel[0] }}">
                                ({{ hotel[1] }}) {{ hotel[2] }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <br/>
            <div class="container text-center">
                <p>Select Account Type</p>
                <div class="form-check form-check-inline">
                    <input class="form-check-input"
                           type="radio"
                           value="customer"
                           name="customer-or-employee-radio"
                           id="customer-radio"
                           checked/>
                    <label class="form-check-label" for="customer-radio">Customer</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input"
                           type="radio"
                           value="employee"
                           name="customer-or-employee-radio"
                           id="employee-radio"/>
                    <label class="form-check-label" for="employee-radio">Employee</label>
                </div>
            </div>
            <br/>
            <div class="container text-center">
                <button type="submit" class="btn btn-dark">Sign Up</button>
            </div>
        </form>
    {% endif %}
{% endblock %}
{% block script %}
    <script type="text/javascript"
            src="{{ url_for('static', filename='sign_up.js') }}"></script>
{% endblock %}